#!/usr/bin/env python3
import sys
from PyQt4 import QtGui
from scudcloud import ScudCloud
if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    app.setApplicationName(ScudCloud.APP_NAME)
    main = ScudCloud()
    main.showMaximized()
    sys.exit(app.exec_())
